[workspace]
members = ["app", "gateway"]

[workspace.package]
edition = "2021"
license = "gpl-3.0-only"
license-file = "LICENSE"
publish = false
readme = "README.md"
repository = "https://github.com/MarzipanClub/marzichat"
rust-version = "1.70.0"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
anyhow = "1.0.71"
const_format = "0.2.31"
leptos = {version = "0.3.1", default-features = false, features = [
  "serde",
]}
leptos_meta = {version = "0.3.1", default-features = false}
leptos_router = {version = "0.3.1", default-features = false}
serde = "1.0.164"
thiserror = "1.0.40"
tokio = {version = "1.28.2", default-features = false}
