[workspace]
members = ["common", "server", "app"]

[workspace.package]
edition = "2021"
publish = false
rust-version = "1.70.0"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
# shared dependencies
anyhow = "1.0.70"
leptos = {version = "0.3.0", default-features = false, features = [
  "serde",
]}
leptos_meta = {version = "0.3.0", default-features = false}
leptos_router = {version = "0.3.0", default-features = false}
serde = "1.0.163"
thiserror = "1.0.40"
