# This file is used by rustfmt to format the code in this repository.
# We override the default settings to with additional formatting paramters with the use of this file.
# For additional settings, see: https://rust-lang.github.io/rustfmt

# Replace strings of _ wildcards by a single .. in tuple patterns
condense_wildcard_suffixes = true

# Reorder impl items. type and const are put first, then macros and methods.
reorder_impl_items = true

# Convert #![doc] and #[doc] attributes to //! and /// doc comments.
normalize_doc_attributes = true

# Convert /* */ comments to // comments where possible
normalize_comments = true

# How imports should be grouped into use statements. Imports will be merged or split to the configured level of granularity.
imports_granularity = "One"

# Controls the strategy for how imports are grouped together.
group_imports = "One"

# Format code snippet included in doc comments.
format_code_in_doc_comments = true

# Break comments to fit on the line
wrap_comments = true

# Use field initialize shorthand if possible.
use_field_init_shorthand = true

# Replace uses of the try! macro by the ? shorthand
use_try_shorthand = true
